version: "3.7"

services:

  app:
    build: ./
    container_name: app
    restart: always
    environment:
      - APP_NAME=LRUCache
    expose:
      - 5000
  redis:
    image: "redis:alpine"

  rqworker:
    image: app
    command: python app.py rqworker